
#pragma once

#define CH_CFG_ST_FREQUENCY 1000

#define CH_CFG_ST_TIMEDELTA 0

#define CH_CFG_TIME_QUANTUM 20

#define CH_CFG_FACTORY_OBJECTS_REGISTRY TRUE

#define CH_CFG_FACTORY_GENERIC_BUFFERS TRUE

#define CH_CFG_FACTORY_SEMAPHORES TRUE

#define CH_CFG_FACTORY_MAILBOXES TRUE

#define CH_CFG_FACTORY_OBJ_FIFOS TRUE

#define CH_CFG_FACTORY_PIPES TRUE

#define CH_DBG_SYSTEM_STATE_CHECK TRUE

#define CH_DBG_ENABLE_CHECKS TRUE

#define CH_DBG_ENABLE_ASSERTS TRUE

#define CH_DBG_ENABLE_STACK_CHECK TRUE

#define CH_DBG_FILL_THREADS TRUE

#include_next <chconf.h>
